const answers = [
    { risk: 1, message: "You can deploy today" },
    { risk: 1, message: "Today is a good day for deployment" },
    { risk: 1, message: "Conditions are favorable for deploying" },
    { risk: 1, message: "Proceed with your deployment plans" },
    { risk: 1, message: "The environment is stable for deployment" },
    { risk: 1, message: "It's a green light for deployment" },
    { risk: 1, message: "Feel confident in deploying today" },
    { risk: 1, message: "You have a green light for deployment" },
    { risk: 1, message: "Deploy away! Today is a good day" },
    { risk: 1, message: "All systems are a go for deployment" },
    { risk: 1, message: "The deployment path is clear today" },
    { risk: 1, message: "No obstacles in your way for deployment" },
    { risk: 1, message: "Today's a great day for releasing code" },
    { risk: 1, message: "The deployment gods smile upon you" },
    { risk: 1, message: "Conditions are ripe for deployment" },
    { risk: 1, message: "Today's a safe bet for deploying" },
    { risk: 1, message: "You're cleared for deployment today" },
    { risk: 1, message: "The coast is clear for deployment" },
    { risk: 1, message: "Green light to deploy your code today" },
    { risk: 1, message: "All signs point to a successful deployment" },
    { risk: 1, message: "The deployment stars are aligned today" },
    { risk: 1, message: "No red flags for deployment today" },
    { risk: 1, message: "Today is a favorable day for deployment" },
    { risk: 1, message: "You're in the clear for deploying today" },
    { risk: 1, message: "It's a good day to release your code" },
    { risk: 1, message: "Conditions are optimal for deployment" },
    { risk: 1, message: "You're on solid ground for deploying" },
    { risk: 1, message: "No storm clouds in sight for deployment" },
    { risk: 1, message: "Today is a green light for deploying" },
    { risk: 1, message: "You have a thumbs up for deployment" },
    { risk: 1, message: "Deploy confidently, it's a good day" },
    { risk: 1, message: "All systems are a go for deployment today" },
    { risk: 1, message: "The runway is clear for deployment" },
    { risk: 1, message: "No roadblocks for deployment today" },
    { risk: 1, message: "Today's a solid day for releasing code" },
    { risk: 1, message: "The deployment winds are in your favor" },
    { risk: 1, message: "Conditions are favorable for releasing code" },
    { risk: 1, message: "Today's a safe bet for deploying code" },
    { risk: 1, message: "You're in the clear for releasing code today" },
    { risk: 1, message: "It's a good day to deploy your code" },
    { risk: 1, message: "Conditions are optimal for releasing code" },
    { risk: 1, message: "You're on solid ground for releasing code" },
    { risk: 1, message: "No storm clouds in sight for releasing code" },
    { risk: 1, message: "Today is a green light for releasing code" },
    { risk: 1, message: "You have a thumbs up for releasing code" },
    { risk: 1, message: "Deploy confidently, it's a good day to do so" },
    { risk: 1, message: "All systems are a go for releasing code today" },
    { risk: 1, message: "The runway is clear for releasing code" },
    { risk: 1, message: "No roadblocks for releasing code today" },
    { risk: 1, message: "Today's a solid day for deploying your code" },
    { risk: 1, message: "The deployment winds are in your favor today" },
    { risk: 1, message: "Conditions are favorable for deploying your code" },
    { risk: 1, message: "Today's a safe bet for releasing your code" },
    { risk: 1, message: "You're in the clear for deploying your code today" },
    { risk: 1, message: "It's a good day to release your code to the world" },
    { risk: 1, message: "Conditions are optimal for deploying your code" },
    { risk: 1, message: "You're on solid ground for deploying your code" },
    { risk: 1, message: "No storm clouds in sight for deploying your code" },
    { risk: 1, message: "Today is a green light for deploying your code" },
    { risk: 1, message: "You have a thumbs up for deploying your code" },
    { risk: 1, message: "Deploy confidently, it's a good day to do so!" },
    { risk: 1, message: "All systems are a go for deploying your code today" },
    { risk: 1, message: "The runway is clear for deploying your code" },
    { risk: 1, message: "No roadblocks for deploying your code today" },
    { risk: 1, message: "Today's a solid day for releasing your code" },
    { risk: 1, message: "The deployment winds are in your favor today" },
    { risk: 1, message: "Conditions are favorable for releasing your code" },
    { risk: 1, message: "Today's a safe bet for deploying your code" },
    { risk: 1, message: "You're in the clear for releasing your code today" },
    { risk: 1, message: "It's a good day to deploy your code to the world" },
    { risk: 1, message: "Conditions are optimal for releasing your code" },
    { risk: 1, message: "You're on solid ground for releasing your code" },
    { risk: 1, message: "No storm clouds in sight for releasing your code" },
    { risk: 1, message: "Today is a green light for releasing your code" },
    { risk: 1, message: "You have a thumbs up for releasing your code" },
    { risk: 1, message: "Deploy confidently, it's a good day to do so!" },
    { risk: 1, message: "All systems are a go for releasing your code today" },
    { risk: 1, message: "The runway is clear for releasing your code" },
    { risk: 1, message: "No roadblocks for releasing your code today" },
    { risk: 1, message: "Today's a solid day for deploying your code to the world" },
    { risk: 1, message: "The deployment winds are in your favor today" },
    { risk: 2, message: "Proceed with caution, there's moderate risk" },
    { risk: 2, message: "Consider a lighter deploy given the moderate risk" },
    { risk: 2, message: "Exercise caution, risk levels are moderate" },
    { risk: 2, message: "You can proceed, but keep a watchful eye" },
    { risk: 2, message: "You may want to opt for a lighter deploy today" },
    { risk: 2, message: "Keep an eye out for potential risks during deploy" },
    { risk: 2, message: "Moderate risk today, consider smaller changes" },
    { risk: 2, message: "You're good to go, but stay vigilant" },
    { risk: 2, message: "Consider a cautious approach to deployment" },
    { risk: 2, message: "Proceed, but be mindful of the moderate risk" },
    { risk: 2, message: "You have the green light, but watch for risks" },
    { risk: 2, message: "Deploy with care, there's moderate risk today" },
    { risk: 2, message: "Moderate risk level, keep changes minimal" },
    { risk: 2, message: "You're cleared, but be cautious of the risk" },
    { risk: 2, message: "Proceed, but be aware of the moderate risk" },
    { risk: 2, message: "Consider a lighter deploy due to moderate risk" },
    { risk: 2, message: "You're in the clear, but stay cautious" },
    { risk: 2, message: "Keep risks in mind as you proceed with deploy" },
    { risk: 2, message: "Moderate risk, opt for a lighter deploy" },
    { risk: 2, message: "You're good to go, just be aware of the risk" },
    { risk: 2, message: "Caution advised, there's moderate risk today" },
    { risk: 2, message: "Proceed, but consider a smaller deploy" },
    { risk: 2, message: "You're cleared, but keep an eye on the risk" },
    { risk: 2, message: "Deploy carefully, there's moderate risk" },
    { risk: 2, message: "Moderate risk level, proceed with caution" },
    { risk: 2, message: "You're in the clear, but be cautious of risk" },
    { risk: 2, message: "Keep the risk in mind during deployment" },
    { risk: 2, message: "Moderate risk today, consider minimal changes" },
    { risk: 2, message: "You're good to go, but be mindful of the risk" },
    { risk: 2, message: "Proceed, but be alert to the moderate risk" },
    { risk: 2, message: "Consider a cautious approach due to moderate risk" },
    { risk: 2, message: "You have the green light, but watch for risks" },
    { risk: 2, message: "Deploy with care, there's a moderate risk today" },
    { risk: 2, message: "Moderate risk level, keep changes minimal" },
    { risk: 2, message: "You're cleared, but be cautious of the risk" },
    { risk: 2, message: "Proceed, but be aware of the moderate risk" },
    { risk: 2, message: "Consider a lighter deploy due to moderate risk" },
    { risk: 2, message: "You're in the clear, but stay cautious" },
    { risk: 2, message: "Keep risks in mind as you proceed with deploy" },
    { risk: 2, message: "Moderate risk, opt for a lighter deploy" },
    { risk: 2, message: "You're good to go, just be aware of the risk" },
    { risk: 2, message: "Caution advised, there's moderate risk today" },
    { risk: 2, message: "Proceed, but consider a smaller deploy" },
    { risk: 2, message: "You're cleared, but keep an eye on the risk" },
    { risk: 2, message: "Deploy carefully, there's moderate risk" },
    { risk: 2, message: "Moderate risk level, proceed with caution" },
    { risk: 2, message: "You're in the clear, but be cautious of risk" },
    { risk: 2, message: "Keep the risk in mind during deployment" },
    { risk: 2, message: "Moderate risk today, consider minimal changes" },
    { risk: 2, message: "You're good to go, but be mindful of the risk" },
    { risk: 2, message: "Proceed, but be alert to the moderate risk" },
    { risk: 2, message: "Consider a cautious approach due to moderate risk" },
    { risk: 2, message: "You have the green light, but watch for risks" },
    { risk: 2, message: "Deploy with care, there's a moderate risk today" },
    { risk: 3, message: "High risk, consider postponing deployment" },
    { risk: 3, message: "Proceed with extreme caution, high risk level" },
    { risk: 3, message: "Deploying today is highly risky, reconsider" },
    { risk: 3, message: "High risk situation, consider alternative plans" },
    { risk: 3, message: "Today is not the day for a high-risk deploy" },
    { risk: 3, message: "Serious risks today, strongly consider delaying" },
    { risk: 3, message: "High risk level, a deploy is not advisable" },
    { risk: 3, message: "Considerable risk today, think twice about deploying" },
    { risk: 3, message: "Deploying today may lead to serious issues" },
    { risk: 3, message: "High potential for issues, delay deployment" },
    { risk: 3, message: "Proceeding today may lead to significant problems" },
    { risk: 3, message: "High-risk scenario, think twice before deploying" },
    { risk: 3, message: "Deploying today could have severe consequences" },
    { risk: 3, message: "High risk level, deployment is not recommended" },
    { risk: 3, message: "Consider postponing, today's risk level is severe" },
    { risk: 3, message: "Deploying today is highly discouraged" },
    { risk: 3, message: "High risk, deploying may lead to critical issues" },
    { risk: 3, message: "Considerable risk today, think carefully about deploying" },
    { risk: 3, message: "Deploying today may have serious repercussions" },
    { risk: 3, message: "High potential for major problems, delay deployment" },
    { risk: 3, message: "Proceeding today may lead to severe complications" },
    { risk: 3, message: "High-risk scenario, deploying is strongly discouraged" },
    { risk: 3, message: "Deploying today could result in severe consequences" },
    { risk: 3, message: "High risk level, it's not advisable to deploy" },
    { risk: 3, message: "Consider postponing, risk level is extremely high" },
    { risk: 3, message: "Deploying today is highly inadvisable" },
    { risk: 3, message: "High risk, deploying could lead to critical issues" },
    { risk: 3, message: "Considerable risk today, think long and hard about deploying" },
    { risk: 3, message: "Deploying today may lead to serious repercussions" },
    { risk: 3, message: "High potential for major problems, it's best to delay deployment" },
    { risk: 3, message: "Proceeding today may lead to severe and lasting complications" },
    { risk: 3, message: "High-risk scenario, it's strongly advised not to deploy" },
    { risk: 3, message: "Deploying today could have severe and lasting consequences" },
    { risk: 3, message: "High risk level, deploying is strongly discouraged" },
    { risk: 3, message: "Consider postponing, today's risk level is extremely high" },
    { risk: 3, message: "Deploying today is highly ill-advised" },
    { risk: 3, message: "High risk, deploying could result in critical issues" },
    { risk: 3, message: "Considerable risk today, it's best to think long and hard before deploying" },
    { risk: 3, message: "Deploying today may result in serious and lasting repercussions" },
    { risk: 3, message: "High potential for major problems, it's best to delay deployment" },
    { risk: 3, message: "Proceeding today may lead to severe and long-lasting complications" },
    { risk: 3, message: "High-risk scenario, it's strongly advised against deploying" },
    { risk: 3, message: "Deploying today could lead to severe and long-lasting consequences" },
    { risk: 3, message: "High risk level, it's highly discouraged to deploy" },
    { risk: 3, message: "Consider postponing, risk level is extremely high" },
    { risk: 3, message: "Deploying today is strongly discouraged" },
    { risk: 3, message: "High risk, deploying could lead to critical and long-lasting issues" },
    { risk: 3, message: "Considerable risk today, it's best to think long and hard before deploying" },
    { risk: 3, message: "Deploying today may result in serious and long-lasting repercussions" },
    { risk: 3, message: "High potential for major problems, it's best to delay deployment" },
    { risk: 3, message: "Proceeding today may lead to severe and long-lasting complications" },
    { risk: 3, message: "High-risk scenario, it's strongly advised against deploying" },
    { risk: 3, message: "Deploying today could lead to severe and long-lasting consequences" },
    { risk: 3, message: "High risk level, it's highly discouraged to deploy" },
    { risk: 3, message: "Consider postponing, risk level is extremely high" }
]